Repository amtoine/nu-git-manager, pull requests merged in 2023-11, with the labels that each got.

#54 clone the Nupm repo with a single depth
  .github/workflows/ci.yml
Labels: ci

#53 test the Nupm installation
  .github/workflows/ci.yml
  tests/mod.nu
Labels: ci, tests

#59 add missing tests
  tests/mod.nu
Labels: tests

#58 add internal documentation
  src/nu-git-manager/fs/cache.nu
  src/nu-git-manager/fs/store.nu
  src/nu-git-manager/git/url.nu
  src/nu-git-manager/mod.nu
  tests/mod.nu
Labels: documentation, enhancement, core

#60 refactor the `error make`s in `error/error.nu`
  src/nu-git-manager/error/error.nu
  src/nu-git-manager/mod.nu
Labels: refactor

#64 use `^git` in the tests
  tests/mod.nu
Labels: core, refactor

#67 add expected `assert error` to the tests
  tests/mod.nu
Labels: tests, core

#65 show the stdout of the tests
  .github/workflows/ci.yml
Labels: ci

#48 test `gm` commands end to end
  src/nu-git-manager/mod.nu
  tests/gm.nu
Labels: tests, core

#72 add install command to the toolkit
  toolkit.nu
Labels: enhancement, dev

#74 update the `gm` examples
  src/nu-git-manager/mod.nu
Labels: documentation

#75 refactor: move completions to their own module
  src/nu-git-manager/completions/nu-complete.nu
  src/nu-git-manager/mod.nu
Labels: core, refactor

#82 feat: setup nightly flow
  .github/actions/setup_nupm/action.yml
  .github/actions/sync_action/action.yml
  .github/workflows/check_nightly.yml
  .github/workflows/ci.yml
  .github/workflows/nupm-tests.yml
  .github/workflows/sync_nightly.yml
Labels: ci, dev

#87 show the Git config and the worktree in the sync CI
  .github/actions/sync_action/action.yml
Labels: ci

#88 fix sync CI by cloning the repo
  .github/actions/sync_action/action.yml
Labels: ci, fix

#89 push with SSH
  .github/actions/sync_action/action.yml
Labels: ci, fix

#90 fix sync CI by giving SSH token to `actions/checkout`
  .github/actions/sync_action/action.yml
  .github/workflows/sync_nightly.yml
Labels: ci, fix

#91 ci: ✨ explicit permissions
  .github/workflows/sync_nightly.yml
Labels: ci

#84 fix: do not allow invalid user-package import in the tests
  tests/gm.nu
Labels: fix, core

#45 Fixes for 0.86.1
  src/nu-git-manager-sugar/gist.nu
  src/nu-git-manager-sugar/git.nu
Labels: fix, nightly, sugar

#62 check if output of `input list` is `null`
  src/nu-git-manager/mod.nu
Labels: enhancement, core

#61 fix `$.span` in `error make`
  src/nu-git-manager-sugar/gist.nu
  src/nu-git-manager-sugar/git.nu
  src/nu-git-manager/error/error.nu
Labels: fix, sugar, core

#77 add a command to clean the store from empty directories
  src/nu-git-manager/fs/dir.nu
  src/nu-git-manager/mod.nu
  tests/gm.nu
  tests/mod.nu
Labels: bug, enhancement, core

#38 use `glob --exclude` instead of `glob --not`
  src/nu-git-manager/fs/store.nu
Labels: fix, core

#63 allow to merge forks
  .github/actions/sync_action/action.yml
  .github/workflows/nupm-tests.yml
  src/nu-git-manager/error/error.nu
  src/nu-git-manager/fs/cache.nu
  src/nu-git-manager/git/repo.nu
  src/nu-git-manager/mod.nu
  tests/gm.nu
  tests/mod.nu
Labels: enhancement, core

#94 mention the nightly branch in the readme
  README.md
Labels: documentation

#95 bump the version to 0.3.0
  package.nuon
Labels: dev

#99 use external action to merge branches
  .github/actions/sync_action/action.yml
  .github/workflows/check_nightly.yml
  .github/workflows/sync_nightly.yml
Labels: ci

#98 use external action to setup Nupm
  .github/actions/setup_nupm/action.yml
  .github/workflows/ci.yml
  .github/workflows/nupm-tests.yml
Labels: ci

#102 use `generate` instead of `unfold`
  src/nu-git-manager/fs/dir.nu
Labels: fix, core

#100 refactor duplicate root stripping
  src/nu-git-manager/fs/path.nu
  src/nu-git-manager/fs/store.nu
  src/nu-git-manager/mod.nu
  tests/mod.nu
Labels: core, refactor

#105 use `^git` instead of `git`
  tests/gm.nu
  tests/mod.nu
Labels: core, refactor

#104 clean sugar git
  src/nu-git-manager-sugar/git.nu
  src/nu-git-manager/git/repo.nu
  tests/sugar/git.nu
  tests/sugar/mod.nu
Labels: enhancement, sugar

#107 add a few examples to `nu-git-manager-sugar git` commands
  src/nu-git-manager-sugar/git.nu
Labels: documentation, enhancement, sugar

#108 use `nupm install --no-confirm` in `tests install-package`
  tests/mod.nu
Labels: tests

#109 collect the output of `git rev-parse`
  src/nu-git-manager-sugar/git.nu
Labels: fix, sugar

#110 use switch forwarding to simplify `github.nu`
  src/nu-git-manager-sugar/github.nu
Labels: fix, nightly, sugar

#111 fix `gm gh pr checkout`: user quit and no PR
  src/nu-git-manager-sugar/github.nu
Labels: fix, sugar

#30 add some sugar
  src/nu-git-manager-sugar/extra.nu
  src/nu-git-manager-sugar/git.nu
  tests/mod.nu
  tests/sugar/git.nu
  tests/sugar/mod.nu
Labels: enhancement, sugar

#112 add a new `--interactive` switch to `toolkit.nu run`
  toolkit.nu
Labels: dev

#113 more granular and complete user import tests
  tests/common/import.nu
  tests/gm.nu
  tests/sugar/mod.nu
Labels: tests, sugar

#114 add type annotations to `toolkit.nu` and fix a bug
  toolkit.nu
Labels: fix, dev

#115 add `get-ignored-tests` to `toolkit.nu`
  toolkit.nu
Labels: enhancement, dev

#117 better live environment in the toolkit
  toolkit.nu
Labels: dev

#118 format
  tests/sugar/mod.nu
Labels: refactor
